### ISSUE TITLE
Missing "return" into the getVolume method

### ISSUE THREAD

**Issue by pebdev** [joeybab3/sonos#1]
Hi,

There is no "return" in this function : 
`uint8_t SonosUPnP::getVolume(IPAddress speakerIP)`

**Comment by joeybab3** [comment]
Yes, there is a second function that is overloaded later https://github.com/joeybab3/sonos/blob/62b61c5b1474f3f4b29255431c1a9115b5e9d3a2/src/SonosUPnP.cpp#L517

Does the function work though? Last I tested it did but I will do some debugging and make sure it does if not.

**Comment by pebdev** [comment]
Yes, the second function works well

**Comment by joeybab3** [comment]
The second function overloads the first one, calling the first one calls the second.

**Comment by pebdev** [comment]
Yes for sure :)

**Comment by joeybab3** [comment]
I can confirm that the examples still work and are able to pull the volume so it appears that it is successfully returning a value for getVolume()

**Comment by pebdev** [comment]
Be careful, you forgot the context :)

Depending on the context, your memory access can succeed, yes, if the register used by the ESP32 to store returned value is not overwritten. But it's very random because : 
- the return instruction is not present (so how compiler can know that it must save register value ?)
- a full context on uC is not just a main "thread", all registers can be overwritten at any time. This type of instructions exist to ensure that the context remains consistent.

It's for this reason, in my case, the volume returned by this function has, some time,  a good value (ex:36) or random value (ex:108764345).
```
uint8_t SonosUPnP::getVolume(IPAddress speakerIP)
{
  getVolume(speakerIP, SONOS_CHANNEL_MASTER);
}
```

But with this function, it works at 100%
```
uint8_t SonosUPnP::getVolume(IPAddress speakerIP, const char *channel)
{
  PGM_P path[] = { p_SoapEnvelope, p_SoapBody, p_GetVolumeR, p_CurrentVolume };
  char result[5] = "0";
  upnpGetString(
    speakerIP, UPNP_RENDERING_CONTROL, p_GetVolumeA,
    SONOS_TAG_CHANNEL, channel, path, 4, result, sizeof(result));
	Serial.print("Result:");
	Serial.println(result);
  return constrain(atoi(result), 0, 100);
}
```

**Comment by joeybab3** [comment]
So shouold I just add `return` to `getVolume(speakerIP, SONOS_CHANNEL_MASTER);`?

**Comment by pebdev** [comment]
Yes exactly.

This, will fix this issue :
```
uint8_t SonosUPnP::getVolume(IPAddress speakerIP)
{
  return getVolume(speakerIP, SONOS_CHANNEL_MASTER);
}
```

**Comment by joeybab3** [comment]
Alright should be done, thanks for bringing it to my attention. It appears some other functions also do not have return statements so I'll have to look into that.

**Comment by pebdev** [comment]
You're welcome ;)
